#!/bin/bash

# This script provides a simple interface for running the integration tests in docker

# Default image names
testImage=quay.io/blockstack/blockstack-integration-tests
coreImage=quay.io/blockstack/blockstack-core
testTag=latest
coreTag=dev
gitCommit=$(git rev-parse --short HEAD)
repoDir=$(git rev-parse --show-toplevel)
gitBranch=$(git rev-parse --abbrev-ref HEAD)
testDir=$repoDir/integration_tests

# Dockerfiles
devDF=$testDir/docker/Dockerfile.dev
testDF=$testDir/docker/Dockerfile.tests

# Test output
outputDir=$testDir/test-out
testOutputDir=$outputDir/$gitBranch-$gitCommit

# Influx Configuration
influxHost="monitoring.technofractal.com"
influxUser="admin"
influxPass="INSERTHERE"

# Set the number of containers to run to the number of logical cores in the system
# This prevents CPU contention in the container which leads to Bitcoind calls timing out
numContainers=1
if [[ $(uname) == 'Linux' ]]; then
  # Pull from /proc/cpuinfo on Linux
  numContainers=$(grep -c ^processor /proc/cpuinfo)
elif [[ $(uname) == 'Darwin' ]]; then
  # Pull from sysctl on Mac
  numContainers=$(sysctl -n hw.logicalcpu)
fi


# Build the test container
build-tests () {
  # First build the blockstack-core:dev image for base of testing image
  echo "Building core image from branch $gitBranch, commit $gitCommit"
  docker build -f $devDF -t $coreImage:$gitCommit $repoDir
  docker tag $coreImage:$gitCommit $coreImage:$coreTag

  # Build testing container from blockstack-core:dev
  echo "Building test image from core image :$gitCommit"
  docker build -f $testDF -t $testImage:$testTag $testDir
}

# Division formatting for percent
percent () {
  awk "BEGIN { pc=100*${1}/${2}; i=int(pc); print (pc-i<0.5)?i:i+1 }"
}

# Shows testing progress
log-progress () {
  local inprogress=$(expr $(docker ps -f status=running -f name="$gitCommit" | wc -l) - 1)
  local completed=$(expr $(docker ps -a -f status=exited -f name="$gitCommit" | wc -l) - 1)
  local totaltests=$(expr $(ls -1 $(pwd)/blockstack_integration_tests/scenarios/ | sed -e 's/\.py$//' | wc -l) - 2)
  local remaining=$(expr $totaltests - $(expr $inprogress + $completed))
  echo "TotalTests: $totaltests, Completed: $(percent $completed $totaltests)%, InProgress: $(percent $inprogress $totaltests)%, Remaining: $(percent $remaining $totaltests)%"
}

# Outputs the array of tests to run
tests () {
  # Get test scenarios
  local scenarios=($(ls -1 $(pwd)/blockstack_integration_tests/scenarios/ | sed -e 's/\.py$//'))

  # Declare arrays for Tests to Skip and Output
  declare -a skips
  declare -a out

  # Make skips array from file
  while read -r line; do
      [[ "$line" =~ ^#.*$ ]] && continue
      skips+=("$line")
  done < "./blockstack_integration_tests/tests_skip.txt"

  # Loop through scenarios
  for sc in "${scenarios[@]}"; do
    if [[ ${skips[*]} =~ $sc ]]; then
      continue
    else
      out+=($sc)
    fi
  done
  echo "${out[@]}"
}

# Runs all the tests in seperate docker containers
run-all () {
  # List of test scenarios to run
  local scenarios=$(tests)

  # Loop through all test scenarios
  for sc in $scenarios; do

    # local variables for each scenario
    local command="blockstack-test-scenario blockstack_integration_tests.scenarios.$sc"

    # Limit number of running docker containers to number of cores on the system
    while [ $(docker ps -q -f status=running -f name="$gitCommit" | wc -l) -ge $numContainers ]; do
      sleep 5
    done

    # Run the docker image, pipe test logs to output folder
    docker run -d --name "$sc-$gitCommit" $testImage:$testTag $command >> /dev/null 2>&1
  done

  # Wait for tests to finish before exiting
  echo "All tests running. Waiting for tests to finish..."
  while [ $(docker ps -q -f status=running -f name="$gitCommit" | wc -l) -ge 0 ]; do
    sleep 10
  done
}

run-one () {
  local outputdir=$testOutputDir/$1/
  local containerdir=/tmp/
  local command="blockstack-test-scenario blockstack_integration_tests.scenarios.$1"

  if [ $# -eq 0 ]; then
    echo "need to input name of test to run"
    echo "to get a list of tests run see blockstack_integration_tests/scenarios"
    exit 1
  fi

  docker run -d --name "$1-$gitCommit-mounted" -v $outputdir:$containerdir $testImage:$testTag $command >> /dev/null 2>&1
}

# Prints out the results in a human readable fashion
check-results () {
  local exited=$(docker ps -a -q  -f status=exited -f name="$gitCommit")
  for test in $exited; do
    local success=$(docker logs $test --tail 100 2>&1 | grep -c "SUCCESS")
    local failure=$(docker logs $test --tail 100 2>&1 | grep -c "FAILURE")
    local name=$(docker inspect -f '{{.Name}}' $test)
    local runtime=$(get-runtime $test)
    if [ $success -eq 1 ]; then
      echo "[ ] SUCCESS in $(expr $runtime / 60)m $(expr $runtime % 60)s -> $name"
    elif [ $failure -eq 1 ]; then
      echo "[X] FAILURE in $(expr $runtime / 60)m $(expr $runtime % 60)s -> $name (docker logs $test)"
    else
      echo "Might want to look at this container: docker logs $test"
    fi
  done
}

# Prints out the results in format for insertion into InfluxDB
write-results () {
  local exited=$(docker ps -a -q  -f status=exited -f name="$gitCommit")
  local reportTime=$(date +%s)
  local importFile=$testDir/influx.txt

  # Clear importFile
  rm -f $importFile

  # Write DDL and DML
  echo "# DDL" >> $importFile
  echo "CREATE DATABASE testing" >> $importFile
  echo "" >> $importFile
  echo "# DML" >> $importFile
  echo "# CONTEXT-DATABASE: testing" >> $importFile
  echo "# CONTEXT-RETENTION-POLICY: autogen" >> $importFile
  echo "" >> $importFile

  # Loop through tests and write points
  for test in $exited; do
    local success=$(docker logs $test --tail 100 2>&1 | grep -c "SUCCESS")
    local failure=$(docker logs $test --tail 100 2>&1 | grep -c "FAILURE")
    local name=$(docker inspect -f '{{.Name}}' $test)
    local runtime=$(get-runtime $test)
    if [ $success -eq 1 ]; then
      echo "integration_tests,git_commit=$gitCommit,git_branch=$gitBranch,test_scenario=$name,success=true runtime=${runtime}i $reportTime" >> $importFile
    elif [ $failure -eq 1 ]; then
      echo "integration_tests,git_commit=$gitCommit,git_branch=$gitBranch,test_scenario=$name,success=false runtime=${runtime}i $reportTime" >> $importFile
    fi
  done

  # Write the data to configured influx instance
  influx -host $influxHost -ssl -username $influxUser -password $influxPass -import -path $importFile -precision "s"

  # Remove the importFile
  rm $importFile
}

# get-runtime $containerID -> gets duration of test in seconds
get-runtime () {
  local started=$(docker inspect $1 -f {{.State.StartedAt}})
  local finished=$(docker inspect $1 -f {{.State.FinishedAt}})
  local sunix=0
  local funix=0
  if [[ $(uname) == 'Linux' ]]; then
    sunix=$(date -d "$started" "+%s")
    funix=$(date -d "$finished" "+%s")
  elif [[ $(uname) == 'Darwin' ]]; then
    sunix=$(date -jf "%FT%T" "$started" "+%s" 2> /dev/null)
    funix=$(date -jf "%FT%T" "$finished" "+%s" 2> /dev/null)
  fi
  expr $funix - $sunix
}

cleanup-docker () {
  echo "Removing all test docker containers..."
  docker stop $(docker ps -a -q -f name="$gitCommit") > /dev/null 2>&1
  docker rm $(docker ps -a -q -f name="$gitCommit") > /dev/null 2>&1
}

cleanup-files () {
  echo "Removing container /tmp data $testOutputDir..."
  rm -rf $testOutputDir
}

commands () {
  cat <<-EOF
blockstack docker launcher commands:
  build-tests -> build the test container
  run-all -> loop through the tests runing 20 at a time
  check-results -> check results from finished tests
  write-results -> write test results to a configured influx instance
  log-progress -> log progress in the test suite
  cleanup-files -> remove all files from test
  cleanup-docker -> cleanup docker containers from test
EOF
}

case $1 in
  build-tests)
    build-tests
    ;;
  run-all)
    run-all
    ;;
  run-one)
    run-one $2
    ;;
  check-results)
    check-results
    ;;
  write-results)
    write-results
    ;;
  log-progress)
    log-progress
    ;;
  cleanup-files)
    cleanup-files
    ;;
  cleanup-docker)
    cleanup-docker
    ;;
  *)
    commands
    ;;
esac
