apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}"
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}"
      labels:
        app: {{ template "fullname" . }}
        release: "{{ .Release.Name }}"
    spec:
      restartPolicy: Never
      containers:
      - name: integration-test-run
        image: "{{ .Values.imageRepo }}:{{ .Values.imageTag }}"
        imagePullPolicy: "Always"
        command: ["blockstack-test-scenario", "blockstack_integration_tests.scenarios.{{ .Values.testName }}"]
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 1000m
            memory: 1Gi
