apiVersion: v1
kind: Pod
metadata:
  name: "{{ .Release.Name }}"
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    test: "{{ .Values.testName }}-{{ .Values.imageTag }}"
spec:
  restartPolicy: Never
  containers:
  - name: integration-test-run
    image: "{{ .Values.imageRepo }}:{{ .Values.imageTag }}"
    imagePullPolicy: "Always"
    command: ["blockstack-test-scenario", "blockstack_integration_tests.scenarios.{{ .Values.testName }}"]
    resources:
      limits:
        cpu: 1000m
      requests:
        cpu: 1000m
        memory: 1Gi
